//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 08:48:29 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://knure.kharkov.ua/jt/st3example")
package ua.kharkov.knure.jt.st3example;
