//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.09 at 01:51:14 PM UTC 
//


package com.epam.rd.java.basic.practice7;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ua.nure package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ua.nure
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Flowers }
     * 
     */
    public Flowers createFlowers() {
        return new Flowers();
    }

    /**
     * Create an instance of {@link Flower }
     * 
     */
    public Flower createFlowersFlower() {
        return new Flower();
    }

    /**
     * Create an instance of {@link GrowingTips }
     * 
     */
    public GrowingTips createFlowersFlowerGrowingTips() {
        return new GrowingTips();
    }

    /**
     * Create an instance of {@link VisualParameters }
     * 
     */
    public VisualParameters createFlowersFlowerVisualParameters() {
        return new VisualParameters();
    }

    /**
     * Create an instance of {@link Tempreture }
     * 
     */
    public Tempreture createFlowersFlowerGrowingTipsTempreture() {
        return new Tempreture();
    }

    /**
     * Create an instance of {@link Lighting }
     * 
     */
    public Lighting createFlowersFlowerGrowingTipsLighting() {
        return new Lighting();
    }

    /**
     * Create an instance of {@link Watering }
     * 
     */
    public Watering createFlowersFlowerGrowingTipsWatering() {
        return new Watering();
    }

    /**
     * Create an instance of {@link AveLenFlower }
     * 
     */
    public AveLenFlower createFlowersFlowerVisualParametersAveLenFlower() {
        return new AveLenFlower();
    }

}
