//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.09 at 01:51:14 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nure.ua", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.epam.rd.java.basic.practice7;
